Consider the below code to answer further questions:

In [2]:
import numpy as np
list_ = ['1','2','3','4','5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Python lists are dynamic arrays, which means that they can grow and shrink in size as needed. Java ArrayLists are also dynamic arrays, but they are implemented differently than Python lists.
Here is a code to print the data types of both the variables:

In [6]:
import numpy as np

list_ = ["1", "2", "3", "4", "5"]
array_list = np.array(object=list_)
print(list_)
print(array_list)
print(type(list_))
print(type(array_list))

['1', '2', '3', '4', '5']
['1' '2' '3' '4' '5']
<class 'list'>
<class 'numpy.ndarray'>


 The variable list_ is a regular Python list, while array_list is a NumPy array.
 NumPy arrays are a more efficient way to store data than regular Python lists,
especially for numerical data. NumPy arrays are also more compact, and they can
 be used to perform mathematical operations more efficiently.

 Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.

In [8]:
for i in list_:
    print(type(i))
for j in array_list:
    print(type(j))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


 Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
 Will there be any difference in the data type of the elements present in both the variables, list_ and
 arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [15]:
array_list = np.array(object=list_, dtype=int)
for i in array_list:
    print(type(i))
for j in list_:
    print(type(j))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


Consider the below code to answer further questions:

In [16]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

 Q4. Write a code to find the following characteristics of variable, num_array:
 (i) shape
 (ii) size

In [17]:
print(num_array.shape)
print(np.size(num_array))

(2, 3)
6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
 creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [14]:
matrix = np.zeros((3, 3))
print(matrix)
print(np.size(matrix))
print(np.shape(matrix))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
9
(3, 3)


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [ ]:
arr = np.array([1,1,1,1,1])
print(np.diag(arr))